version: "3"
services:
  node:
    image: node
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
  postgres:
    image: postgres
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
